stages:
  - lint
  - test
  - build
  - deploy

variables:
  MYSQL_DATABASE: your_database_name
  MYSQL_ROOT_PASSWORD: your_root_password

lint:
  stage: lint
  image: php:7.4-cli
  before_script:
    - apt-get update && apt-get install -y wget
    - wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v3.8.0/php-cs-fixer.phar -O php-cs-fixer
    - chmod a+x php-cs-fixer
  script:
    - ./php-cs-fixer fix --dry-run --diff

test:
  stage: test
  image: php:7.4-cli
  services:
    - mysql:5.7
  before_script:
    - apt-get update && apt-get install -y libzip-dev zip unzip git
    - docker-php-ext-install pdo pdo_mysql zip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install
  script:
    - vendor/bin/phpunit

build:
  stage: build
  image: node:14
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts
    - rsync -avz --delete dist/ $DEPLOY_USER@$DEPLOY_SERVER_IP:$DEPLOY_PATH
  only:
    - main